main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('pastas/', views.pastas_index, name='index'),
    path('pastas/<int:pasta_id>/', views.pastas_detail, name='detail'),
    path('pastas/create', views.PastaCreate.as_view(), name='pastas_create'),
    path('pastas/<int:pk>/update', views.PastaUpdate.as_view(), name='pastas_update'),
    path('pastas/<int:pk>/delete', views.PastaDelete.as_view(), name='pastas_delete'),
    path('pastas/<int:pasta_id>/add_dish/', views.add_dish, name='add_dish'),
]

pastacollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
# Import the reverse function
from django.urls import reverse

PASTA_TYPES = (
    ('SM', 'Small Pasta'),
    ('RC', 'Ribbon-Cut'),
    ('TS', 'Tube-Shaped'),
    ('ST', 'Stuffed')
)

DIFFICULTY = (
    ('E', 'Easy'),
    ('M', 'Moderate'),
    ('D', 'Difficult')
)

# Create your models here.
class Pasta(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(
        max_length=2,
        choices=PASTA_TYPES,
        default=PASTA_TYPES[0][0],
        )
    cook_time = models.IntegerField()

    def __str__(self):
        return self.name
    
    # handle redirect to detail page
    def get_absolute_url(self):
        return reverse('detail', kwargs={'pasta_id': self.id})
    
    # SMALL_PASTA = 'Small Pasta'
    # RIBBON_CUT = 'Ribbon-Cut'
    # TUBE_SHAPED = 'Tube-Shaped'
    # STUFFED = 'Stuffed'
    # TYPE_CHOICES = {
    #     SMALL_PASTA: 'Small Pasta',
    #     RIBBON_CUT: 'Ribbon-Cut',
    #     TUBE_SHAPED: 'Tube-Shaped',
    #     STUFFED: 'Stuffed',
    # }

class Dish(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    is_vegetarian = models.BooleanField()
    recipe_link = models.URLField()
    difficulty = models.CharField(
        'cook difficulty',
        max_length=1,
        choices=DIFFICULTY,
        default=DIFFICULTY[1][0]
        )
    # Create a pasta_id FK to satisfy 1:M relationship
    pasta = models.ForeignKey(Pasta, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.name} - {self.get_difficulty_display()} difficulty"
    
    class Meta:
        ordering = ['difficulty']

main_app/forms.py
from django.forms import ModelForm
from .models import Dish

class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = ['name', 'description', 'is_vegetarian', 'recipe_link', 'difficulty']

main_app/views.py
from django.shortcuts import render, redirect

# Import for Class-based Views
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Import Model
from .models import Pasta

# Import ModelForm
from .forms import DishForm

# pastas = [
#     {
#         'name': 'Bucatini',
#         'type': 'Ribbon-Cut',
#         'cook_time': 9
#     },
#     {
#         'name': 'Agnolotti',
#         'type': 'Stuffed',
#         'cook_time': 6
#     },
#     {
#         'name': 'Rigatoni',
#         'type': 'Tube-Shaped',
#         'cook_time': 8
#     }
# ]

# Create your views here.

# HOME VIEW
def home(request):
    return render(request, 'home.html')

# ABOUT VIEW
def about(request):
    return render(request, 'about.html')

# PASTAS INDEX VIEW
def pastas_index(request):
    pastas = Pasta.objects.all() # retrieve all Pastas
    return render(request, 'pastas/index.html', {
        'pastas': pastas,
    })

# PASTAS DETAIL VIEW - GET
def pastas_detail(request, pasta_id):
    pasta = Pasta.objects.get(id=pasta_id) # retreive pasta by id
    dish_form = DishForm() # invoke ModelForm
    return render(request, 'pastas/detail.html', {
        'pasta': pasta,
        'dish_form': dish_form
    })

# PASTAS CREATE CLASS-BASED VIEW
class PastaCreate(CreateView):
    model = Pasta
    fields = '__all__'

# PASTAS UPDATE CLASS-BASED VIEW
class PastaUpdate(UpdateView):
    model = Pasta
    fields = ['type', 'cook_time']

# PASTAS DELETE CLASS-BASED VIEW
class PastaDelete(DeleteView):
    model = Pasta
    success_url = reverse_lazy('index')

# PASTA - CREATE DISH
def add_dish(request, pasta_id):
    form = DishForm(request.POST)
    if form.is_valid():
        new_dish = form.save(commit=False)
        new_dish.pasta_id = pasta_id
        new_dish.save()
    return redirect('detail', pasta_id=pasta_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About Page</h1>
<hr>
<p>Welcome to Pasta Collector, your one-stop shop for learning about various types of pasta shapes.</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Pasta Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Pasta Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'pastas_create' %}">Add a Pasta</a></li>
          <li><a href="{% url 'index' %}">Explore Pastas</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2024 Pasta Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/pasta_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h2>Delete Pasta</h2>
<h4>Are you sure want to delete <span class="green-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, Delete" class="btn">
    <a href="{% url 'detail' pasta.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/pasta_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
<h1>Edit <span class="green-text">{{ object.name }}</span></h1>
{% else %}
<h1>Add Pasta</h1>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
<script>
    pastaTypeEl = document.getElementById('id_type');
    M.FormSelect.init(pastaTypeEl);
</script>
{% endblock %}

main_app/templates/pastas/detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ pasta.name }}</h1>

<div class="row">
  <div>
    <div class="card">
      <div class="card-content">
        <p><strong>Type:</strong> {{ pasta.get_type_display }}</p>
        <p><strong>Cook Time:</strong> {{ pasta.cook_time }} mins</p>
      </div>
      <div class="card-action">
        <a href="/pastas" class="right">All Pastas</a>
        <a href="{% url 'pastas_update' pasta.id %}">Edit</a>
        <a href="{% url 'pastas_delete' pasta.id %}">Delete</a>
      </div>
    </div>
  </div>
  <br />
  <!-- Display cat feedings -->
  <h3>Dishes</h3>
  <div>
    <form action="{% url 'add_dish' pasta.id %}" method="POST">
        {% csrf_token %}
        <!-- Render the inputs -->
        {{ dish_form.as_p }}
        <input type="submit" class="btn" value="Add Dish">
    </form>
      <br />
    <table class="striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Vegetarian</th>
          <th>Recipe</th>
          <th>Difficulty</th>
        </tr>
      </thead>
      <tbody>
        {% for dish in pasta.dish_set.all %}
        <tr>
          <td>{{ dish.name|linebreaks }}</td>
          <td>{{ dish.description|linebreaks }}</td>
          <td>{{ dish.is_vegetarian }}</td>
          <td><a href="{{ dish.recipe_link }}" target="_blank" rel="noopener noreferrer">View</a></td>
          <td>{{ dish.get_difficulty_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
    const difficultyEl = document.getElementById('id_difficulty');
    M.FormSelect.init(difficultyEl);
</script>
{% endblock %}

main_app/templates/pastas/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Types of Pastas</h1>

{% for pasta in pastas %}
<a href="{% url 'detail' pasta.id %}">
<div class="card">
    <div class="card-content black-text">
        <span class="card-title">{{ pasta.name }}</span>
        <p><strong>Type:</strong> {{ pasta.get_type_display }}</p>
        <p><strong>Cook Time:</strong> {{ pasta.cook_time }} mins</p>
    </div>
</div>
</a>
{% endfor %}

{% if pastas %}
<p>Total Pastas:
{{ pastas|length }}</p>
{% else %}
<p>There are no pastas yet.</p>
{% endif %}

{% endblock %}